### ISSUE TITLE
cargo test: compiler error

### ISSUE THREAD

**Issue by Ploppz** [dsferruzza/actix-web-middleware-keycloak-auth#6]
On latest master, with latest nightly rustc.

```
error[E0599]: no method named `wrap_api` found for struct `App` in the current scope
  --> examples/paperclip.rs:73:14
   |
73 |             .wrap_api()
   |              ^^^^^^^^ method not found in `App<impl ServiceFactory<ServiceRequest, Response = ServiceResponse<middleware::logger::StreamLog<AnyBody>>, Error = actix_web::Error, Config = (), InitError = ()>, middleware::logger::StreamLog<AnyBody>>`
```

**Comment by dsferruzza** [comment]
I guess this is because you need the `paperclip_compat` feature to compile this example; see: https://github.com/dsferruzza/actix-web-middleware-keycloak-auth/blob/master/examples/paperclip.rs#L6-L7

(Also, paperclip does not support actix web 4 yet. This is why I use a fork here: https://github.com/dsferruzza/actix-web-middleware-keycloak-auth/blob/master/Cargo.toml#L25 But as this dependency is pulled via Git (instead of crates.io) I had to make it under a feature because crates.io does not consider dependencies that are not pulled via crates.io.)
